<a href="https://colab.research.google.com/github/yyic1203/Cuantica/blob/main/cuantica_taller_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Librerias

In [ ]:
import numpy as np
import sympy as sp
from numpy.linalg import eig

#Ejercicio 3.3

In [ ]:
e1=((197*np.pi)**2)/(2*64*939)
e2=4*e1
e3=9*e1
print('El valor de energía 1 es: ', e1)
print('El valor de energía 2 es: ', e2)
print('El valor de energía 3 es: ', e3)

El valor de energía 1 es:  3.186813408561941
El valor de energía 2 es:  12.747253634247764
El valor de energía 3 es:  28.68132067705747


In [ ]:
P=e1*(2/7)+e2*(1/7)+e3*(4/7)
print('La energía promedio es: ', P)

La energía promedio es:  19.120880451371647


#Ejercicio 3.12

In [ ]:
H = np.array([[-2, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

A = np.array([[5, 0, 0],
              [0, 0, 2],
              [0, 2, 0]])
C1=np.dot(H,A)
C2=np.dot(A,H)
chl=C1-C2
print(' C1: ', C1)
print('C2: ', C2)
print('El conmutador es: ', chl)

 C1:  [[-10   0   0]
 [  0   0   2]
 [  0   2   0]]
C2:  [[-10   0   0]
 [  0   0   2]
 [  0   2   0]]
El conmutador es:  [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
autovalores_H, autovectores_H = eig(H)
autovalores_A, autovectores_A = eig(A)

print(' Los autovalores de H son: ', autovalores_H)
print('Los autovectores de H son: ', autovectores_H)
print(' Los autovalores de A son: ', autovalores_A)
print('Los autovectores de A son: ', autovectores_A)


 Los autovalores de H son:  [-2.  1.  1.]
Los autovectores de H son:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 Los autovalores de A son:  [ 2. -2.  5.]
Los autovectores de A son:  [[ 0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.70710678 -0.70710678  0.        ]]


#Ejercicio 3.16

In [ ]:
# Definimos las matrices H y A utilizando objetos de matriz de sympy
H_sympy = sp.Matrix([
    [0, -sp.I, 0],
    [sp.I, 0, 2*sp.I],
    [0, -2*sp.I, 0]
])

A_sympy = sp.Matrix([
    [0, -sp.I, 0],
    [sp.I, 1, 1],
    [0, 1, 0]
])

# Calculamos los autovalores y autovectores con sympy
autovectores_H, autovalores_H = H_sympy.diagonalize()
autovectores_A, autovalores_A = A_sympy.diagonalize()

eig_H = H_sympy.eigenvects()
eig_A = A_sympy.eigenvects()

# Simplificamos y presentamos los resultados
eig_H_simplified = [(val, mult, [sp.simplify(vec.normalized()) for vec in vecs]) for val, mult, vecs in eig_H]
eig_A_simplified = [(val, mult, [sp.simplify(vec.normalized()) for vec in vecs]) for val, mult, vecs in eig_A]

print(' Los autovalores de H son: ', autovalores_H)
print('Los autovectores de H son: ', eig_H_simplified)
print(' Los autovalores de A son: ', autovalores_A)
print('Los autovectores de A son: ', eig_A_simplified)


 Los autovalores de H son:  Matrix([[0, 0, 0], [0, -sqrt(5), 0], [0, 0, sqrt(5)]])
Los autovectores de H son:  [(0, 1, [Matrix([
[-2*sqrt(5)/5],
[           0],
[   sqrt(5)/5]])]), (-sqrt(5), 1, [Matrix([
[ sqrt(10)/10],
[-sqrt(2)*I/2],
[  sqrt(10)/5]])]), (sqrt(5), 1, [Matrix([
[sqrt(10)/10],
[sqrt(2)*I/2],
[ sqrt(10)/5]])])]
 Los autovalores de A son:  Matrix([[-1, 0, 0], [0, 0, 0], [0, 0, 2]])
Los autovectores de A son:  [(-1, 1, [Matrix([
[-sqrt(3)*I/3],
[  -sqrt(3)/3],
[   sqrt(3)/3]])]), (0, 1, [Matrix([
[sqrt(2)*I/2],
[          0],
[  sqrt(2)/2]])]), (2, 1, [Matrix([
[-sqrt(6)*I/6],
[   sqrt(6)/3],
[   sqrt(6)/6]])])]
