<a href="https://colab.research.google.com/github/yyic1203/Cuantica/blob/main/Cu%C3%A1ntica_parcial_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Librerias

In [ ]:
import numpy as np
import sympy as sp
from numpy.linalg import eig

#Punto 2

In [ ]:
# Definir las variables simbólicas
theta, phi = sp.symbols('theta phi')

# Crear la matriz simbólica
matrix = sp.Matrix([
    [sp.cos(theta), sp.sin(theta)*sp.exp(-sp.I*phi), 0],
    [sp.sin(theta)*sp.exp(sp.I*phi), sp.cos(theta), 0],
    [0, 0, 1]
])

# Calcular autovalores y autovectores
autovectores, autovalores = matrix.diagonalize()
vec_a=matrix.eigenvects()

print(' Los autovalores de H son: ', autovalores)
print('Los autovectores de H son: ', autovectores)


 Los autovalores de H son:  Matrix([[1, 0, 0], [0, -sin(theta) + cos(theta), 0], [0, 0, sin(theta) + cos(theta)]])
Los autovectores de H son:  Matrix([[0, -exp(-I*phi), exp(-I*phi)], [0, 1, 1], [1, 0, 0]])
 La matriz diagonalizada es:  Matrix([[-sin(theta), -exp(-I*phi)*cos(theta), exp(-I*phi)], [exp(I*phi)*sin(theta), cos(theta), 1], [cos(theta), exp(-I*phi)*sin(theta), 0]])


# Punto 3




a. Compatibilidad


In [ ]:
#Conmutador
A = sp.Matrix([[10, 2, 0],
              [2, 10, 0],
              [0, 0, 12]])

B = sp.Matrix([[5, 1, 0],
              [1, 5, 0],
              [0, 0, 3]])


 AB:  [[52 20 0]
 [20 52 0]
 [0 0 36]]
BA:  [[52 20 0]
 [20 52 0]
 [0 0 36]]
El conmutador es:  [[0 0 0]
 [0 0 0]
 [0 0 0]]


Autovectores

In [ ]:
# Calcular autovalores y autovectores
autovectores_B, autovalores_B = B.diagonalize()
autovectores_A, autovalores_A = A.diagonalize()


print(' Los autovalores de A son: ', autovalores_A)
print('Los autovectores de A son: ', autovectores_A)
print(' Los autovalores de B son: ', autovalores_B)
print('Los autovectores de B son: ', autovectores_B)

 Los autovalores de A son:  Matrix([[8, 0, 0], [0, 12, 0], [0, 0, 12]])
Los autovectores de A son:  Matrix([[-1, 1, 0], [1, 1, 0], [0, 0, 1]])
 Los autovalores de B son:  Matrix([[3, 0, 0], [0, 4, 0], [0, 0, 6]])
Los autovectores de B son:  Matrix([[0, -1, 1], [0, 1, 1], [1, 0, 0]])


In [ ]:
A_1 = np.array([[10, 2, 0],
              [2, 10, 0],
              [0, 0, 12]])
B_1 = np.array([[5, 1, 0],
              [1, 5, 0],
              [0, 0, 3]])
AB=np.dot(A_1,B_1)
BA=np.dot(B,A)
C=AB-BA
print(' AB: ', AB)


autovalores_A_1, autovectores_A_1 = np.linalg.eig(A_1)
autovalores_B_1, autovectores_B_1 = np.linalg.eig(B_1)

autovalores_AB, autovectores_AB = np.linalg.eig(AB)

print(' Los autovalores de A son: ', autovalores_A_1)
print('Los autovectores de A son: ', autovectores_A_1)
print(' Los autovalores de B son: ', autovalores_B_1)
print('Los autovectores de B son: ', autovectores_B_1)

print(' Los autovalores de AB son: ', autovalores_AB)
print('Los autovectores de AB son: ', autovectores_AB)

 AB:  [[52 20  0]
 [20 52  0]
 [ 0  0 36]]
 Los autovalores de A son:  [12.  8. 12.]
Los autovectores de A son:  [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
 Los autovalores de B son:  [6. 4. 3.]
Los autovectores de B son:  [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
 Los autovalores de AB son:  [72. 32. 36.]
Los autovectores de AB son:  [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
